# Aula 05

## Importar as bibliotecas

In [ ]:
# Importar as bibliotecas
import numpy as np
import pandas as pd

## Criando o "dataset do caos"

In [ ]:
# Criar o conjunto de dados com dados faltantes
dados_sujos = {
    'ID_Pedido': [101, 102, 103, 103, 105, 106, 107, 108, 109, 110],
    'Cliente': ['Ana', 'Bruno', 'Carlos', 'Carlos', 'Eva',
                'Frank', np.nan, 'Hannah', 'Ítalo', 'Julia'],
    'Valor': [150.50, np.nan, 200.00, 200.00, 50.00,
              -999, 120.00, np.nan, 300.00, 450.00],
    'Status': ['Pago', 'Pendente', 'Pago', 'Pago', 'pago',
               'Cancelado', 'Pendente', 'Pendente', 'Enviado', 'Enviado'],
    'Data': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-03', '2023-01-05',
             np.nan, '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10']
}

df = pd.DataFrame(dados_sujos)
print('Dataset "sujo" carregado')
df

Dataset "sujo" carregado

   ID_Pedido Cliente  Valor     Status        Data
0        101     Ana  150.5       Pago  2023-01-01
1        102   Bruno    NaN   Pendente  2023-01-02
2        103  Carlos  200.0       Pago  2023-01-03
3        103  Carlos  200.0       Pago  2023-01-03
4        105     Eva   50.0       pago  2023-01-05
5        106   Frank -999.0  Cancelado         NaN
6        107     NaN  120.0   Pendente  2023-01-07
7        108  Hannah    NaN   Pendente  2023-01-08
8        109   Ítalo  300.0    Enviado  2023-01-09
9        110   Julia  450.0    Enviado  2023-01-10

## Detectando o inimigo: valores nulos (`NaN`)

In [ ]:
# Contagem de nulos por coluna
print('Valores nulos por coluna:')
df.isnull().sum()

Valores nulos por coluna:

ID_Pedido    0
Cliente      1
Valor        2
Status       0
Data         1
dtype: int64

In [ ]:
# Porcentagem de dados faltantes
percentual_nulos = (df.isnull().sum() / len(df)) * 100
print(f'Percentual de nulos:\n{percentual_nulos}')

Percentual de nulos:
ID_Pedido     0.0
Cliente      10.0
Valor        20.0
Status        0.0
Data         10.0
dtype: float64

## Tratamento de nulos: `dropna` e `fillna`

### `dropna()`: a opção nuclear

In [ ]:
# Remover as linhas que possuem valores NaN
df_limpo = df.dropna(
    axis=0,
    how='any',  # 'any': ao menos um NaN na linha / 'all': todas as células com NaN
)
df_limpo

   ID_Pedido Cliente  Valor   Status        Data
0        101     Ana  150.5     Pago  2023-01-01
2        103  Carlos  200.0     Pago  2023-01-03
3        103  Carlos  200.0     Pago  2023-01-03
4        105     Eva   50.0     pago  2023-01-05
8        109   Ítalo  300.0  Enviado  2023-01-09
9        110   Julia  450.0  Enviado  2023-01-10

In [ ]:
# Remover apenas se o nulo estiver em uma coluna específica
df_cliente_ok = df.dropna(subset=['Cliente'])
df_cliente_ok

   ID_Pedido Cliente  Valor     Status        Data
0        101     Ana  150.5       Pago  2023-01-01
1        102   Bruno    NaN   Pendente  2023-01-02
2        103  Carlos  200.0       Pago  2023-01-03
3        103  Carlos  200.0       Pago  2023-01-03
4        105     Eva   50.0       pago  2023-01-05
5        106   Frank -999.0  Cancelado         NaN
7        108  Hannah    NaN   Pendente  2023-01-08
8        109   Ítalo  300.0    Enviado  2023-01-09
9        110   Julia  450.0    Enviado  2023-01-10

### `fillna()`: a opção cirúrgica

In [ ]:
# Preencher o valor nulo com a média (estratégia comum)
media_valor = round(df['Valor'].mean(), 2)
df['Valor'] = df['Valor'].fillna(media_valor)
df

   ID_Pedido Cliente   Valor     Status        Data
0        101     Ana  150.50       Pago  2023-01-01
1        102   Bruno   58.94   Pendente  2023-01-02
2        103  Carlos  200.00       Pago  2023-01-03
3        103  Carlos  200.00       Pago  2023-01-03
4        105     Eva   50.00       pago  2023-01-05
5        106   Frank -999.00  Cancelado         NaN
6        107     NaN  120.00   Pendente  2023-01-07
7        108  Hannah   58.94   Pendente  2023-01-08
8        109   Ítalo  300.00    Enviado  2023-01-09
9        110   Julia  450.00    Enviado  2023-01-10

In [ ]:
# Preencher com uma constante
df['Cliente'] = df['Cliente'].fillna('Desconhecido')
df

   ID_Pedido       Cliente   Valor     Status        Data
0        101           Ana  150.50       Pago  2023-01-01
1        102         Bruno   58.94   Pendente  2023-01-02
2        103        Carlos  200.00       Pago  2023-01-03
3        103        Carlos  200.00       Pago  2023-01-03
4        105           Eva   50.00       pago  2023-01-05
5        106         Frank -999.00  Cancelado         NaN
6        107  Desconhecido  120.00   Pendente  2023-01-07
7        108        Hannah   58.94   Pendente  2023-01-08
8        109         Ítalo  300.00    Enviado  2023-01-09
9        110         Julia  450.00    Enviado  2023-01-10

In [ ]:
# Preencher com o valor da linha anterior (ótimo para séries temporais)
df['Data'] = df['Data'].fillna(method='ffill')
df

/tmp/ipykernel_8004/864327355.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Data'] = df['Data'].fillna(method='ffill')

   ID_Pedido       Cliente   Valor     Status        Data
0        101           Ana  150.50       Pago  2023-01-01
1        102         Bruno   58.94   Pendente  2023-01-02
2        103        Carlos  200.00       Pago  2023-01-03
3        103        Carlos  200.00       Pago  2023-01-03
4        105           Eva   50.00       pago  2023-01-05
5        106         Frank -999.00  Cancelado  2023-01-05
6        107  Desconhecido  120.00   Pendente  2023-01-07
7        108        Hannah   58.94   Pendente  2023-01-08
8        109         Ítalo  300.00    Enviado  2023-01-09
9        110         Julia  450.00    Enviado  2023-01-10

## Removendo duplicatas

In [ ]:
# Vereficaar se há duplicatas
print(f'Total de duplicatas: {df.duplicated().sum()}')

Total de duplicatas: 1

In [ ]:
# Remover duplicatas mantendo apenas a primeira ocorrência
df = df.drop_duplicates(keep='first')
df

   ID_Pedido       Cliente   Valor     Status        Data
0        101           Ana  150.50       Pago  2023-01-01
1        102         Bruno   58.94   Pendente  2023-01-02
2        103        Carlos  200.00       Pago  2023-01-03
4        105           Eva   50.00       pago  2023-01-05
5        106         Frank -999.00  Cancelado  2023-01-05
6        107  Desconhecido  120.00   Pendente  2023-01-07
7        108        Hannah   58.94   Pendente  2023-01-08
8        109         Ítalo  300.00    Enviado  2023-01-09
9        110         Julia  450.00    Enviado  2023-01-10

## Substituição e padronização: `replace`

In [ ]:
# Corrigir valores impossíveis
df['Valor'] = df['Valor'].replace(-999, 0)
df

/tmp/ipykernel_8004/1952476810.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Valor'] = df['Valor'].replace(-999, 0)

   ID_Pedido       Cliente   Valor     Status        Data
0        101           Ana  150.50       Pago  2023-01-01
1        102         Bruno   58.94   Pendente  2023-01-02
2        103        Carlos  200.00       Pago  2023-01-03
4        105           Eva   50.00       pago  2023-01-05
5        106         Frank    0.00  Cancelado  2023-01-05
6        107  Desconhecido  120.00   Pendente  2023-01-07
7        108        Hannah   58.94   Pendente  2023-01-08
8        109         Ítalo  300.00    Enviado  2023-01-09
9        110         Julia  450.00    Enviado  2023-01-10

In [ ]:
# Padronizar os valores de uma coluna
df['Status'] = df['Status'].replace('pago', 'Pago')
df

/tmp/ipykernel_8004/4056036537.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Status'] = df['Status'].replace('pago', 'Pago')

   ID_Pedido       Cliente   Valor     Status        Data
0        101           Ana  150.50       Pago  2023-01-01
1        102         Bruno   58.94   Pendente  2023-01-02
2        103        Carlos  200.00       Pago  2023-01-03
4        105           Eva   50.00       Pago  2023-01-05
5        106         Frank    0.00  Cancelado  2023-01-05
6        107  Desconhecido  120.00   Pendente  2023-01-07
7        108        Hannah   58.94   Pendente  2023-01-08
8        109         Ítalo  300.00    Enviado  2023-01-09
9        110         Julia  450.00    Enviado  2023-01-10

In [ ]:
# Substituição múltipla usando dicionário
correcoes = {
    'Pendente': 'Aguardando',
    'Enviado': 'Em trânsito'
}
df['Status'] = df['Status'].replace(correcoes)
df

/tmp/ipykernel_8004/1464869965.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Status'] = df['Status'].replace(correcoes)

   ID_Pedido       Cliente   Valor       Status        Data
0        101           Ana  150.50         Pago  2023-01-01
1        102         Bruno   58.94   Aguardando  2023-01-02
2        103        Carlos  200.00         Pago  2023-01-03
4        105           Eva   50.00         Pago  2023-01-05
5        106         Frank    0.00    Cancelado  2023-01-05
6        107  Desconhecido  120.00   Aguardando  2023-01-07
7        108        Hannah   58.94   Aguardando  2023-01-08
8        109         Ítalo  300.00  Em trânsito  2023-01-09
9        110         Julia  450.00  Em trânsito  2023-01-10

|Ferramenta|Quando usar|
|:-:|:-:|
|`isnull().sum()`|Para diagnosticar onde estão os valores `NaNs`|
|`dropna()`|Quando você tem muitos dados e pode se dar ao luxo de perder linhas|
|`fillna()`|Quando perder dados causa viés; usa-se média, mediana ou moda|
|`drop_duplicates()`|Essencial após unir tabelas ou ler logs de sistemas|
|`replace()`|Para limpar erros de digitação ou valores sentinela|