# Aula 06

## Criar o dataset

In [ ]:
# --- Importar o Pandas --- #
import pandas as pd

# --- Criar os dados --- #
dados = {
    'Cod_Produto': ['TECH-001', 'SOFT-002', 'TECH-003', 'GEAR-004'],
    'Descricao': [' notebook gamer v1', 'LICENÇA ANTIVÍRUS',
                  'monitor 4k ultra', ' MOUSE SEM FIO '],
    'Preco_Unitario': ['1500.00', '299.99', '3200.00', '150.00'],
    'Quantidade': [10, 50, 5, 100],
    'Custo_Percentual': [0.7, 0.2, 0.6, 0.4]
}

df = pd.DataFrame(dados)
df

  Cod_Produto           Descricao Preco_Unitario  Quantidade  Custo_Percentual
0    TECH-001   notebook gamer v1        1500.00          10               0.7
1    SOFT-002   LICENÇA ANTIVÍRUS         299.99          50               0.2
2    TECH-003    monitor 4k ultra        3200.00           5               0.6
3    GEAR-004      MOUSE SEM FIO          150.00         100               0.4

In [ ]:
# --- Ver as informações dos dados --- #
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Cod_Produto       4 non-null      object
 1   Descricao         4 non-null      object
 2   Preco_Unitario    4 non-null      object
 3   Quantidade        4 non-null      int64
 4   Custo_Percentual  4 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 292.0+ bytes

## Conversão de tipos: o poder do `astype`

In [ ]:
# --- Converter de string para float --- #
df['Preco_Unitario'] = df['Preco_Unitario'].astype(float)

# --- Verificar a mudança --- #
print(f'Novo tipo da coluna "Preco_Unitario": {df["Preco_Unitario"].dtype}')

Novo tipo da coluna "Preco_Unitario": float64

## Operações aritméticas (vetorização)

In [ ]:
# --- Calcular a receita total --- #
df['Receita_Total'] = df['Preco_Unitario'] * df['Quantidade']

# --- Calcular o custo real --- #
df['Custo_Total'] = df['Receita_Total'] * df['Custo_Percentual']

# --- Calcular a margem de lucro --- #
df['Lucro_Liquido'] = df['Receita_Total'] - df['Custo_Total']

df[['Cod_Produto', 'Receita_Total', 'Lucro_Liquido']]

  Cod_Produto  Receita_Total  Lucro_Liquido
0    TECH-001        15000.0         4500.0
1    SOFT-002        14999.5        11999.6
2    TECH-003        16000.0         6400.0
3    GEAR-004        15000.0         9000.0

## Manipulação de strings com `.str`

In [ ]:
# --- Remover os espaços em branco e padronizar a escrita --- #
df['Descricao'] = df['Descricao'].str.strip().str.title()

# --- Criar uma coluna de Categoria a partir de Cod_Produto --- #
# --- O expland=True transforma o resultado em colunas separadas --- #
df['Categoria'] = df['Cod_Produto'].str.split('-', expand=True)[0]

# --- Verificara se há uma substring --- #
df['Eh_Gamer'] = df['Descricao'].str.contains('gamer', case=False)
df[['Cod_Produto', 'Categoria', 'Descricao', 'Eh_Gamer']]

  Cod_Produto Categoria          Descricao  Eh_Gamer
0    TECH-001      TECH  Notebook Gamer V1      True
1    SOFT-002      SOFT  Licença Antivírus     False
2    TECH-003      TECH   Monitor 4K Ultra     False
3    GEAR-004      GEAR      Mouse Sem Fio     False

## Métodos de string essenciais

|Método|O que faz
|:-:|:-:|
|`str.lower()`/`.upper()`|Muda a caixa do texto.|
|`str.replace('A', 'B')`|Substitui caracteres|
|`str.len()`|Conta o número de caracteres|
|`.str.slice(0, 3)`|Corta a string|