# Aula 04

In [2]:
# Importar o Pandas
import pandas as pd

## Preparando os dados

In [3]:
# Criar os dados
dados = {
    'Nome': ['Alice', 'Bruno', 'Carla', 'Davi',
             'Eduarda', 'Fernando', 'Gabriela', 'Heitor'],
    'Departamento': ['TI', 'TI', 'TI', 'Vendas',
                     'Marketing', 'TI', 'Vendas', 'Marketing'],
    'Salário': [8500, 9200, 5000, 4200,
                6000, 10500, 3800, 7200],
    'Anos experiência': [5, 6, 3, 1,
                         4, 8, 2, 5],
    'Remoto': [True, False, False, True,
               True, False, False, True]
}

df = pd.DataFrame(dados).set_index('Nome')

df

         Departamento  Salário  Anos experiência  Remoto
Nome
Alice              TI     8500                 5    True
Bruno              TI     9200                 6   False
Carla              TI     5000                 3   False
Davi           Vendas     4200                 1    True
Eduarda     Marketing     6000                 4    True
Fernando           TI    10500                 8   False
Gabriela       Vendas     3800                 2   False
Heitor      Marketing     7200                 5    True

## .iloc: Seleção por posição (coordenadas)

In [5]:
# Selecionar a primeira linha e a primeira coluna
df.iloc[0, 0]  # linha, coluna

'TI'

In [6]:
# Selecionar as 3 primeiras linhas e todas as colunas
df.iloc[0:3, :]

      Departamento  Salário  Anos experiência  Remoto
Nome
Alice           TI     8500                 5    True
Bruno           TI     9200                 6   False
Carla           TI     5000                 3   False

In [7]:
# Selecionar as colunas 1 e 2 para as linhas 4 a 6
df.iloc[4:7, 1:3]

          Salário  Anos experiência
Nome
Eduarda      6000                 4
Fernando    10500                 8
Gabriela     3800                 2

## .loc: Seleção por rótulo (índice)

In [8]:
# Selecionar todos os dados de Gabriela
df.loc['Gabriela']

Departamento        Vendas
Salário               3800
Anos experiência         2
Remoto               False
Name: Gabriela, dtype: object

In [9]:
# Selecionar o salário e departamento
df.loc[['Bruno', 'Fernando'], ['Salário', 'Departamento']]

          Salário Departamento
Nome
Bruno        9200           TI
Fernando    10500           TI

In [10]:
# Fatiar o conjunto
df.loc['Alice': 'Eduarda', 'Salário']

Nome
Alice      8500
Bruno      9200
Carla      5000
Davi       4200
Eduarda    6000
Name: Salário, dtype: int64

## Máscara booleanas

In [21]:
# Mostrar os dados a partir de uma condição
df_salario = df['Salário'] > 7000
df[df_salario]

         Departamento  Salário  Anos experiência  Remoto
Nome
Alice              TI     8500                 5    True
Bruno              TI     9200                 6   False
Fernando           TI    10500                 8   False
Heitor      Marketing     7200                 5    True

In [18]:
# Aplicar condições para a seleção dos dados (E)
filtro_e = (df['Departamento'] == 'TI') & (df['Remoto'] == True)
df[filtro_e]

      Departamento  Salário  Anos experiência  Remoto
Nome
Alice           TI     8500                 5    True

In [23]:
# Aplicar condições para a seleção dos dados (OU)
filtro_ou = (df['Salário'] < 5000) | (df['Anos experiência'] < 4)
df[filtro_ou]

         Departamento  Salário  Anos experiência  Remoto
Nome
Carla              TI     5000                 3   False
Davi           Vendas     4200                 1    True
Gabriela       Vendas     3800                 2   False

## O método .query(): elegância SQL

In [24]:
# Mais legível que por conector lógico
limite = 5000
busca = df.query('Salário > @limite and Departamento == "Marketing"')
busca

        Departamento  Salário  Anos experiência  Remoto
Nome
Eduarda    Marketing     6000                 4    True
Heitor     Marketing     7200                 5    True