# Aula 07

## Criando o Dataset

In [1]:
# --- Importar o Pandas --- #
import pandas as pd

# --- Criar os dados --- #
dados = {
    'regiao': ['Norte', 'Norte', 'Sul', 'Sul', 'Norte', 'Sul', 'Oeste', 'Oeste'],
    'vendedor': ['Ana', 'Bruno', 'Carlos', 'Diego', 'Ana', 'Diego', 'Erika', 'Erika'],
    'produto': ['Celular', 'Tablet', 'Celular', 'Notebook', 'Notebook', 'Tablet', 'Celular', 'Monitor'],
    'vendas': [2500, 1200, 2500, 4500, 3800, 1300, 2600, 1500],
    'comissao': [125, 60, 125, 225, 190, 65, 130, 75]
}

# --- Criar o DataFrame --- #
df = pd.DataFrame(dados)
df

  regiao vendedor   produto  vendas  comissao
0  Norte      Ana   Celular    2500       125
1  Norte    Bruno    Tablet    1200        60
2    Sul   Carlos   Celular    2500       125
3    Sul    Diego  Notebook    4500       225
4  Norte      Ana  Notebook    3800       190
5    Sul    Diego    Tablet    1300        65
6  Oeste    Erika   Celular    2600       130
7  Oeste    Erika   Monitor    1500        75

## Groupby Básico: Agregação Simples

In [6]:
# --- Qual o valor total de vendas por região? --- #
vendas_regiao = df.groupby('regiao')['vendas'].sum()
vendas_regiao

regiao
Norte    7500
Oeste    4100
Sul      8300
Name: vendas, dtype: int64

In [9]:
# --- Transformar o agrupamento em um DataFrame --- #
vendas_regiao_df = df.groupby('regiao')[['vendas']].sum()
vendas_regiao_df

        vendas
regiao
Norte     7500
Oeste     4100
Sul       8300

## O Poder do `.agg()`: Agregações Customizadas

In [12]:
# --- Aplicar múltiplas funções a uma coluna --- #
resumo_vendas = df.groupby('regiao')['vendas'].agg(['sum', 'mean', 'count', 'max'])
resumo_vendas

         sum         mean  count   max
regiao
Norte   7500  2500.000000      3  3800
Oeste   4100  2050.000000      2  2600
Sul     8300  2766.666667      3  4500

### Agregações Diferentes por Coluna

In [14]:
# --- Separar as agregações por coluna --- #
dic_agg = {
    'vendas': 'sum',
    'comissao': 'mean'
}

resumo_especifico = df.groupby('regiao').agg(dic_agg)
resumo_especifico

        vendas    comissao
regiao
Norte     7500  125.000000
Oeste     4100  102.500000
Sul       8300  138.333333

## Agregação Nomeada

In [18]:
# --- Nomear as colunas agrupadas --- #
resumo_vendedor = df.groupby('vendedor').agg(
    total_vendido=('vendas', 'sum'),
    media_comissao=('comissao', 'mean'),
    qtd_produtos=('produto', 'count')
)

resumo_vendedor.sort_values(by='total_vendido', ascending=False)

          total_vendido  media_comissao  qtd_produtos
vendedor
Ana                6300           157.5             2
Diego              5800           145.0             2
Erika              4100           102.5             2
Carlos             2500           125.0             1
Bruno              1200            60.0             1

## Agrupamento por Múltiplas Colunas

In [23]:
# --- Agrupar os dados por mais colunas --- #
multi_grupo = df.groupby(['regiao', 'produto'])[['vendas']].sum()
multi_grupo

                 vendas
regiao produto
Norte  Celular     2500
       Notebook    3800
       Tablet      1200
Oeste  Celular     2600
       Monitor     1500
Sul    Celular     2500
       Notebook    4500
       Tablet      1300

|Técnica|Objetvo|
|:-:|:-:|
|`df.groupby('A')['B'].sum()`|Agregação mais simples e rápida|
|`.agg(['mean', 'std'])`|Várias estatísticas para a mesma coluna|
|`.agg({'A': 'sum', 'B': 'max'})`|Funções diferentes para colunas diferentes|
|**Agregação Nomeada**|O jeito mais limpo de gerar relatórios com nomes de colunas customizados|