# Aula 08

## Preparando o Dataset

In [ ]:
# --- Importar o Pandas --- #
import pandas as pd

# --- Criar os dados --- #
dados = {
    'Loja': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Trimestre': ['Q1', 'Q2', 'Q1', 'Q2', 'Q1', 'Q2'],
    'Vendas': [1000, 1500, 800, 1200, 2000, 2100]
}

# --- Criar o DataFrame --- #
df = pd.DataFrame(dados)
df

  Loja Trimestre  Vendas
0    A        Q1    1000
1    A        Q2    1500
2    B        Q1     800
3    B        Q2    1200
4    C        Q1    2000
5    C        Q2    2100

## `pivot_table`: Tornando o Dado "Largo"

In [ ]:
# --- A pivot_table é como a tabela dinâmica no Excel --- #
df_pivot = df.pivot_table(
    values='Vendas',  # o que vai dentro da tabela
    index='Loja',  # quem será o index
    columns='Trimestre',  # quem será a coluna
    aggfunc='sum'  # a operação de agregação
)

# --- Mostrar a tabela pivotada --- #
df_pivot

Trimestre    Q1    Q2
Loja
A          1000  1500
B           800  1200
C          2000  2100

##`melt`: Tornando o Dado "Longo"

In [ ]:
# --- "Derreter" a tabela --- #
df_melted = df_pivot.reset_index().melt(
    id_vars='Loja',  # index da tabela pivotada
    var_name='Trimestre',  # colunas a serem separadas
    value_name='Vendas'  # o que irá dentro da tabela
)

# --- Mostrar a tabela "derretida" --- #
df_melted

  Loja Trimestre  Vendas
0    A        Q1    1000
1    B        Q1     800
2    C        Q1    2000
3    A        Q2    1500
4    B        Q2    1200
5    C        Q2    2100

## `stack` e `unstack`: O Nível Hierárquico

- `stack`: Empilha as colunas para o índice (transforma **largo** em **longo**)
- `unstack`: Desempilha o índice para as colunas (transforma **longo** em **largo**)

In [ ]:
# --- Criar um índice hierárquico --- #
df_hierarquico = df.set_index(['Loja', 'Trimestre'])
df_hierarquico

                Vendas
Loja Trimestre
A    Q1           1000
     Q2           1500
B    Q1            800
     Q2           1200
C    Q1           2000
     Q2           2100

In [ ]:
# --- Unstack: move "Trimestre" para as colunas --- #
df_unstacked = df_hierarquico.unstack()
df_unstacked

          Vendas
Trimestre     Q1    Q2
Loja
A           1000  1500
B            800  1200
C           2000  2100

In [ ]:
# --- Stack: move "Trimestre" para o índice --- #
df_stacked = df_unstacked.stack()
df_stacked

/tmp/ipykernel_515/626788889.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_stacked = df_unstacked.stack()

                Vendas
Loja Trimestre
A    Q1           1000
     Q2           1500
B    Q1            800
     Q2           1200
C    Q1           2000
     Q2           2100

|**Método**|**Objetico**|**Direção**|
|:-:|:-:|:-:|
|`pivot_table`|Criar relatórios comparativos|Longo -> Largo|
|`melt`|Preparar gráficos ou ML|Largo -> Longo|
|`unstack`|Mover índice para coluna|Longo -> Largo|
|`stack`|Mover coluna para índice|Largo -> Longo|