# Aula 09

## Criando os dados

In [1]:
# --- Importar o Pandas --- #
import pandas as pd

# --- Tabela A: Clientes --- #
df_clientes = pd.DataFrame({
    'ID_Cliente': [1, 2, 3, 4],
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Diego'],
    'Estado': ['SP', 'RJ', 'MG', 'BA']
})

# --- Tabela B: Pedidos --- #
df_pedidos = pd.DataFrame({
    'Cod_Cliente': [1, 2, 2, 3, 5],
    'Item': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Cadeira Gamer'],
    'Valor': [5000, 150, 300, 1500, 1200]
})

In [2]:
df_clientes

   ID_Cliente    Nome Estado
0           1     Ana     SP
1           2   Bruno     RJ
2           3  Carlos     MG
3           4   Diego     BA

In [3]:
df_pedidos

   Cod_Cliente           Item  Valor
0            1       Notebook   5000
1            2          Mouse    150
2            2        Teclado    300
3            3        Monitor   1500
4            5  Cadeira Gamer   1200

## O método `merge()` e os tipos de cruzamento

### Inner Join (interceção)
Traz apenas o que existe em **ambas** as tabelas

In [5]:
# --- left_on e right_on são usados porque as colunas têm nomes diferentes --- #
df_inner = pd.merge(
    left=df_clientes,
    right=df_pedidos,
    left_on='ID_Cliente',
    right_on='Cod_Cliente',
    how='inner'
)
df_inner

   ID_Cliente    Nome Estado  Cod_Cliente      Item  Valor
0           1     Ana     SP            1  Notebook   5000
1           2   Bruno     RJ            2     Mouse    150
2           2   Bruno     RJ            2   Teclado    300
3           3  Carlos     MG            3   Monitor   1500

## Left Join (foco na esquerda)
Traz **todos** os clientes da tabela da esquerda (Clientes). Se alguém não comprou nada (caso do diego), os campos de pedido viram `NaN`

In [6]:
df_left = pd.merge(
    left=df_clientes,
    right=df_pedidos,
    left_on='ID_Cliente',
    right_on='Cod_Cliente',
    how='left'
)
df_left

   ID_Cliente    Nome Estado  Cod_Cliente      Item   Valor
0           1     Ana     SP          1.0  Notebook  5000.0
1           2   Bruno     RJ          2.0     Mouse   150.0
2           2   Bruno     RJ          2.0   Teclado   300.0
3           3  Carlos     MG          3.0   Monitor  1500.0
4           4   Diego     BA          NaN       NaN     NaN

### Right Join (foco na direita)
Traz **todos** os pedidos da tabela da direita. O pedido do cliente ID 5 aparece, mas o nome e o estado dele ficam vazios porque ele não está no cadastro

In [7]:
df_right = pd.merge(
    left=df_clientes,
    right=df_pedidos,
    left_on='ID_Cliente',
    right_on='Cod_Cliente',
    how='right'
)
df_right

   ID_Cliente    Nome Estado  Cod_Cliente           Item  Valor
0         1.0     Ana     SP            1       Notebook   5000
1         2.0   Bruno     RJ            2          Mouse    150
2         2.0   Bruno     RJ            2        Teclado    300
3         3.0  Carlos     MG            3        Monitor   1500
4         NaN     NaN    NaN            5  Cadeira Gamer   1200

### Outer Join (união total)
Traz absolutamente **tudo** de ambas as tabelas, preenchendo com `NaN` onde não houver correspondência

In [8]:
df_outer = pd.merge(
    left=df_clientes,
    right=df_pedidos,
    left_on='ID_Cliente',
    right_on='Cod_Cliente',
    how='outer'
)
df_outer

   ID_Cliente    Nome Estado  Cod_Cliente           Item   Valor
0         1.0     Ana     SP          1.0       Notebook  5000.0
1         2.0   Bruno     RJ          2.0          Mouse   150.0
2         2.0   Bruno     RJ          2.0        Teclado   300.0
3         3.0  Carlos     MG          3.0        Monitor  1500.0
4         4.0   Diego     BA          NaN            NaN     NaN
5         NaN     NaN    NaN          5.0  Cadeira Gamer  1200.0

## O método `concat()`: empilhamento

In [13]:
# --- Simular dados de venda de meses diferentes --- #
vendas_jan = pd.DataFrame({
    'Produto': ['A', 'B'],
    'Qtd': [10, 20]
})
vendas_fev = pd.DataFrame({
    'Produto': ['C', 'A'],
    'Qtd': [15, 30]
})

# --- Empilhar verticalmente (axis=0) --- #
vendas_ano = pd.concat([vendas_jan, vendas_fev], axis=0, ignore_index=True)
vendas_ano

  Produto  Qtd
0       A   10
1       B   20
2       C   15
3       A   30

## O método `join()`: foco em índices

In [18]:
# --- Colocar o ID do cliente como índice --- #
df_clientes_idx = df_clientes.set_index('ID_Cliente')
df_pedidos_idx = df_pedidos.set_index('Cod_Cliente')

# --- O .join() faz um left join por padrão --- #
df_resultado = df_clientes_idx.join(df_pedidos_idx)

df_resultado

     Nome Estado      Item   Valor
1     Ana     SP  Notebook  5000.0
2   Bruno     RJ     Mouse   150.0
2   Bruno     RJ   Teclado   300.0
3  Carlos     MG   Monitor  1500.0
4   Diego     BA       NaN     NaN

|Comando|Quando usar|Chave de ligação|
|:-:|:-:|:-:|
|`pd.merge()`|Cruzamento complexo de tabelas relacionais|Colunas com nomes iguais ou diferentes|
|`pd.concat()`|Juntar arquivos com a mesma estrutura (ex: relatórios mensais)|Alinhamento por nome de coluna ou linha|
|`df.join()`|Quando você já transformou as chaves em índices das tabelas|Sempre através do Index|